### ISSUE TITLE
Dev database

### ISSUE THREAD

**Issue by klsmith-usgs** [USGS-EROS/espa-maintenance#12]
Make sure the dev and test databases appropriately mirror the ops database as far as table schemas and vice versa in the future.

**Comment by klsmith-usgs** [comment]
Something simple to make sure there are no diffs in the schemas and to highlight any operational configurations that other processes might look at/for.

**Comment by dhill-usgs** [comment]
There may actually be intended diffs in the schemas, if changes require db
mods.  The only things I've found that do what you describe are ORMs
(Django does it with migrations) and South.

On Wed, Dec 23, 2015 at 2:21 PM, Kelcy Smith <notifications@github.com>
wrote:

> Something simple to make sure there are no diffs in the schemas and to
> highlight any operational configurations that other processes might look
> at/for.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-EROS/espa-maintenance/issues/12#issuecomment-166984004>
> .
>



-- 
David V. Hill
LSRD
SGT
Contractor to USGS Earth Resources Observation And Science Center (EROS)
47914 252nd Street
Sioux Falls, SD 57198-9801
605.594.2639
dhill@usgs.gov

**Comment by klsmith-usgs** [comment]
I'm just thinking about deployment time, something that can bring attention
to possible configuration differences, not enact them. Such as the email
notifications that I added to dev.

On Wed, Dec 23, 2015 at 2:40 PM, David V. Hill <notifications@github.com>
wrote:

> There may actually be intended diffs in the schemas, if changes require db
> mods. The only things I've found that do what you describe are ORMs
> (Django does it with migrations) and South.
>
> On Wed, Dec 23, 2015 at 2:21 PM, Kelcy Smith <notifications@github.com>
> wrote:
>
> > Something simple to make sure there are no diffs in the schemas and to
> > highlight any operational configurations that other processes might look
> > at/for.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/USGS-EROS/espa-maintenance/issues/12#issuecomment-166984004
> >
> > .
> >
>
>
>
> --
> David V. Hill
> LSRD
> SGT
> Contractor to USGS Earth Resources Observation And Science Center (EROS)
> 47914 252nd Street
> Sioux Falls, SD 57198-9801
> 605.594.2639
> dhill@usgs.gov
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-EROS/espa-maintenance/issues/12#issuecomment-166986472>
> .
>



-- 
Kelcy Smith
Software Engineer
Stinger Ghaffarian Technologies (SGT, Inc.)
Contractor to the U.S. Geological Survey (USGS)
Earth Resources Observation and Science (EROS) Center
47914 252nd St
Sioux Falls, South Dakota 57198
Office: (605) 594-2836
Fax: (605) 594-6529
Email: klsmith@usgs.gov
